aws-user-group-nz/aws-community-day-nz

- index.html
Reverts aws-user-group-nz/aws-community-day-nz#12
> Revert "fix indented issue"

- index.html
The deadline for speaker submissions is July 26.
> [Update] add call for speakers end date

- index.html
- Add google pin to location
- swap sessions and speakers to reduce scrolling on the day
> Add google map pin to locations

- index.html
- js/main.js
- Update the website for AWS Community Day 2024
- The team decided to plan for AWS Community Day 2024 and update the launch accordingly.
> update aws cd 2024 launch page

- index.html
- Update Ram's company name
- Outdated information
> update ram's company name

- css/style.css
- index.html
Add `API Connects` as silver sponsor and some minor changes
> Aws cd 2024 dev

- index.html
- unhides the call for speaker button
> nfc: enable call for speakers

- inperson.html
- update the sponsor pack to v2
> update the sponsor pack

- .gitignore
- css/style.css
- inperson.html
- virtual.html
Adding AWS as platinum sponsors
> Add aws as platinum sponsor

- css/style.css
- inperson.html
- virtual.html
- Added MongoDB and Datacom as Silver Sponsors
- Added CyberCX as Bronze sponsors
- Added Mantel Group as Silver Sponsors
> Add silver & bronze sponsors

- virtual.html
- points to awsusg aotearoa linkedin page
> chore: set linkedin oceanic link

- virtual.html
- update format alignments
- and show schedule links
- update Aotearoa image invalid link
> docs: update virtual content formatting

- inperson.html
> chore: update inperson committee list

- inperson.html
- virtual.html
- adds Deloitte as gold sponsor
> chore: update gold sponsor

- inperson.html
- switch position of schedules and speakers menu
> chore: switch menu position

- inperson.html
- exclude LingLing from speaker list
> chore: update speaker list

- inperson.html
Updating Hrishi's surname spelling
> bugfix: fix spelling mistake

- inperson.html
> chore: update chamila's profile

- inperson.html
> fix: update speakers list

- inperson.html
Reverts aws-user-group-nz/aws-community-day-nz#123
- The team decided at the standup on the 15th of September to remove this from the website.
> Revert "add alert for ticket sales deadline"
